### ISSUE TITLE
Soret coefficient as a callable

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/FESTIM#458]
As discussed with @mougenj, the expression for the Soret coefficient is currently hard coded as Q (or H) = free_enthalpy*T + entropy.
Users should be able to give a callable (function of T):

```python
from FESTIM import Material

def function_Q(T):
    return 2 + 5 * T


my_mat = Material(id=1, D_0=1, E_D=0, Q=function_Q)
```

**Comment by KulaginVladimir** [comment]
Hi, all. What's the status of this issue?

**Comment by RemDelaporteMathurin** [comment]
@KulaginVladimir there was an attempt at fixing this issue in https://github.com/festim-dev/FESTIM/pull/468 however the PR required some work since the drop in coverage hinted towards [variable naming mistakes](https://github.com/festim-dev/FESTIM/pull/468#issuecomment-1126664139)

But I don't think @mougenj had the time to fix this and it felt below the radar.

I believe it would still be beneficial to have the Soret coefficient as either a float or a callable:

```python
from FESTIM import Material

my_mat = Material(id=1, D_0=1, E_D=0, Q=lambda T: 2 + 5 * T)
# or
my_mat = Material(id=1, D_0=1, E_D=0, Q=10)

```

**Comment by KulaginVladimir** [comment]
@RemDelaporteMathurin. I also think it would be useful. So, I can try to implement it soon

**Comment by RemDelaporteMathurin** [comment]
@KulaginVladimir I must admit it is far from being one of my priorities at the moment so feel free to give it a go! I'll assign you to this issue for now then

**Comment by KulaginVladimir** [comment]
@RemDelaporteMathurin, By the way, what do you think of renaming the parameter? Simply, `Q` or `heat_of_transport`?

**Comment by RemDelaporteMathurin** [comment]
> Simply, `Q` or `heat_of_transport`?

we went for D, S for diffusivity and Solubility so I think we can keep Q, as long as it's well documented



> Also, change its unit to `eV` rather than `J/mol`?

I don't know what's the most common? What do you think?

**Comment by KulaginVladimir** [comment]
> I don't know what's the most common? What do you think?

Based on papers that I remember, it is usually defined in eVs. Also, I think that most of 'energy parameters' in FESTIM are expressed in eVs
