### ISSUE TITLE
`Materials`, `Exports`, `DerivedQuantities`, ... should be a subclass of `list`

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/FESTIM#494]
Users should be able to do

```python
my_materials = festim.Materials()

tungsten = festim.Material(....)

my_materials.append(tungsten)
```

To do so, the current Materials class:
https://github.com/festim-dev/FESTIM/blob/621769f7bf56af1bf6a08612c0cd6d269e8f93da/festim/materials/materials.py#L10-L18

Needs to become:

```python
class Materials(list):

    def __init__(self, *args):
        super().__init__(*args)
```

Then instead of doing:

```python
my_materials = festim.Materials(......)

for mat in my_materials.materials:
    ...
```

one would do:
```python
my_materials = festim.Materials(......)

for mat in my_materials:
    ...
```

Moreover, this:
https://github.com/festim-dev/FESTIM/blob/621769f7bf56af1bf6a08612c0cd6d269e8f93da/festim/materials/materials.py#L78

would become:

```python
for mat in self:
```

Progress track:

- [x] `Materials` : #694 
- [x] `Exports` : #695 
- [ ] `DerivedQuantities`: #697 
- [ ] `Traps`: #697

**Comment by KulaginVladimir** [comment]
@RemDelaporteMathurin. Could you please clarify the practical benefit of it a bit more? As I understand, this enhancement will make more like a built-in class, so the users won't need to manually create lists every time and work with them, but rather use documented methods of the FESTIM class (I assume that the docs also will be modified) + some code refactoring. Am I correct?

**Comment by RemDelaporteMathurin** [comment]
1. It is super annoying for users to write

```python
my_materials = F.Materials([....])

second_material = my_materials.materials[1]
```
thanks to this change, this will become much simpler:

```python
my_materials = F.Materials([....])

second_material = my_materials[1]
```

Same for boundary conditions, traps, derivedquantities, exports, and others.

2. it will clear a lot of the code base

**Comment by KulaginVladimir** [comment]
Ok, I can try. How we'll do it:  for all classes at once or iteratively?

**Comment by RemDelaporteMathurin** [comment]
let's start with `Materials`

**Comment by KulaginVladimir** [comment]
@RemDelaporteMathurin, what do you think of `TXT Exports` considering the deprecation?

**Comment by RemDelaporteMathurin** [comment]
> @RemDelaporteMathurin, what do you think of `TXTExports` considering its deprecation?

I would ignore it
