### ISSUE TITLE
`Stepsize` should have a `adapt_when` argument

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/FESTIM#507]
Currently, users can set the `t_stop` argument, which corresponds to the time after which the stepsize should stop adapting (increase or decrease).

However, it could be more flexible if users were able to pass a function of time to determine if it should adapt.

For instance:

```python
def func(t):
    return t < 100

my_stepsize = F.Stepsize(..., adapt_when=func)

```

Or maybe a function that returns a boolean and the maximum stepsize at the same time.

**Comment by KulaginVladimir** [comment]
Looks interesting. I think it can really help when modelling periodic transient events on large timescales.

**Comment by RemDelaporteMathurin** [comment]
@KulaginVladimir do you think it would be better to allow `max_stepsize` to be a function of time or to implement an `adapt_when` argument?

**Comment by KulaginVladimir** [comment]
Personally, max_stepsize appears to be more flexible as we can control both the 'when' event and the step-size value. 

Though, I wonder how it'd work. Assume we set max_stepsize = 1 for 0<t<t1 and max_stepsize = 2 otherwise. After t=t1, the step-size will smoothly rise via adaptation or it'll just jump to 2?

**Comment by RemDelaporteMathurin** [comment]
> After t=t1, the step-size will smoothly rise via adaptation or it'll just jump to 2?

The later. We would basically let the stepsize adapt everytime BUT if max_stepsize(t) is not None, then we cap it to some max_stepsize(t) if it's larger.

**Comment by KulaginVladimir** [comment]
Thus, it's similar to your earlier hint in slack on how to adapt step-size periodically via custom class. Sounds nice! 

Certainly, will add flexibility.

**Comment by KulaginVladimir** [comment]
On the modifications:
If we introduce the `max_stepsize` function, then we don't need `t_stop ` and `stepsize_stop_max `, right? If so, would it be required to keep these attributes for some time and introduce a DeprecationWarning to give the users time to adapt?

**Comment by RemDelaporteMathurin** [comment]
Correct! Maybe keeping them for now with a DeprecationWarning would be a good idea yes
