### ISSUE TITLE
Theory

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/FESTIM#510]
- [ ] Conservation of chemical potential
- [ ] McNabb and Foster equations
- [ ] Soret effect
- [ ] Triangle model, implantation approximation
- [ ] - [ ] Units
- [ ] What's the retention

**Comment by RemDelaporteMathurin** [comment]
@KulaginVladimir as you can see we had planned to write this Theory page for quite some time!

**Comment by KulaginVladimir** [comment]
@RemDelaporteMathurin, I can try to fill this gap
