### ISSUE TITLE
Multiple diffusing species?

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/FESTIM#520]
@stephen-dixon asked during the FESTIM workshop if the implementation of multiple diffusing species was planned.

I thought maybe here would be a good place to kick off the conversation.

Assuming **1 trap** and **2 diffusing species** that can be trapped in it, here are the sets of equations:

$$ \frac{\partial c_\mathrm{m, 1}}{\partial t} = \nabla \cdot (\nabla c_\mathrm{m, 1}) - k \ c_\mathrm{m, 1} \ (n - c_\mathrm{t, 1}- c_\mathrm{t, 2}) + p \ c_\mathrm{t, 1}$$

$$ \frac{\partial c_\mathrm{m, 2}}{\partial t} = \nabla \cdot (\nabla c_\mathrm{m, 2}) - k \ c_\mathrm{m, 2} \ (n - c_\mathrm{t, 1}- c_\mathrm{t, 2}) + p \ c_\mathrm{t, 2} $$

$$ \frac{\partial c_\mathrm{t, 1}}{\partial t} = k \ c_\mathrm{m, 1} \ (n - c_\mathrm{t, 1}- c_\mathrm{t, 2}) - p \ c_\mathrm{t, 1} $$

$$ \frac{\partial c_\mathrm{t, 2}}{\partial t} = k \ c_\mathrm{m, 2} \ (n - c_\mathrm{t, 1}- c_\mathrm{t, 2}) - p \ c_\mathrm{t, 2} $$

where $c_\mathrm{m, 1}$ and $c_\mathrm{m, 2}$ are the concentrations of the 2 diffusing species, $c_\mathrm{t, 1}$ and $c_\mathrm{t, 2}$ are the concentrations of species 1 and 2 trapped.

Now things can get heavy when adding more traps (and more diffusing species!).
It also gets complicated if not all traps can react with all diffusing species (for instance, species 1 can be trapped in trap 1 but not in trap 2).

There is no technical limit of doing such a thing in FEniCS. It would just need to be thought well in terms of implementation!

Is it something you're thinking of adding in ACHLYS?

**Comment by stephen-dixon** [comment]
Hey Remi! Yes, I played around with a formulation a bit like this in MOOSE limited to 2 diffusing species but did't take it very far (with self-diffusion too, but but I'm not sure how significant that is). I hadn't thought about more complicated reaction mechanisms than all species reacting with all traps. Is that inspired by your helium work? One limitation with a single-atom-per-trap model is I don't think it will capture any isotope-exchange of trapped species (e.g. sequential loading of different isotopes). You mentioned in the workshop maybe including an exchange probability or something? Did I mis-hear or do you have something in mind for this?

**Comment by RemDelaporteMathurin** [comment]
@stephen-dixon apologies for never replying to this! Completely missed it!

> Is that inspired by your helium work?

Well, the fundamentals of this are chemical reactions right? You've got two species reacting to create a third, and the opposite reaction also exists.
So ultimately you have a potentially large system of equations for each species.

The "usual" McNabb & Foster equations are just a special case of this where you have only mobile H interacting with empty trap to create trapped H.

> One limitation with a single-atom-per-trap model is I don't think it will capture any isotope-exchange of trapped species

Having several atoms per trap is effectively the same thing. trap-with-1-H reacts with mobile H to create trap-with-2-H.
It can get a bit crazy when you have several atoms per trap _and_ several isotopes, but we'd just have to be careful about the implementation

> Did I mis-hear or do you have something in mind for this?

This is something we'll definitely consider for FESTIM2!! 👀
