### ISSUE TITLE
Using F.t with spline

### ISSUE THREAD

**Issue by nickwinz** [festim-dev/FESTIM#537]
I want to define my temperatures based on experimental measurements, which I have fitted with a spline using `scipy.interpolate.LSQUnivariateSpline`, so something like this:

`my_model.T = F.Temperature(T_spline(F.t))`

This returns an error message; apparently the spline doesn't accept F.t as an input. Presumably I could define a function for the temperature, i.e. T(t), but is there a simpler way of doing this?

**Comment by RemDelaporteMathurin** [comment]
Hi @nickwinz , happy to help with that.

Could you produce a minimal working example of what you're trying to do? That would greatly help solving your issue

**Comment by nickwinz** [comment]
Hi @RemDelaporteMathurin , thanks for your help! My code would look something like this:

```
import festim as F
import numpy as np
from scipy.interpolate import LSQUnivariateSpline

my_model = F.Simulation()

# here are our "experimental measurements" for time and temperature
t_meas = np.linspace(0, 500, 500)
T_meas = 300 + t_meas**1.1

# I want to fit a spline to the experimental data like this:
knots = np.linspace(t_meas[1], t_meas[-2], 100)
T_spline = LSQUnivariateSpline(t_meas, T_meas, knots, k=3)

# now I want to define the temperature for the model
my_model.T = F.Temperature(T_spline(F.t))
```

**Comment by RemDelaporteMathurin** [comment]
Awesome thanks for this MWE! (as a general rule of thumb, providing such MWEs greatly helps for debugging and support)

I'll have a look asap (spoiler: I think I know how to get what you want!)

**Comment by RemDelaporteMathurin** [comment]
@nickwinz could you try the following:

```python
import festim as F
import numpy as np
from scipy.interpolate import LSQUnivariateSpline

my_model = F.Simulation()

# here are our "experimental measurements" for time and temperature
t_meas = np.linspace(0, 500, 500)
T_meas = 300 + t_meas**1.1

# I want to fit a spline to the experimental data like this:
knots = np.linspace(t_meas[1], t_meas[-2], 100)
T_spline = LSQUnivariateSpline(t_meas, T_meas, knots, k=3)

# Create our own Temperature class
import fenics as f
class CustomT(F.Temperature):  # inherit from FESTIM.Temperature

    def update(self, t):  # override the update method
        """Updates T_n, expression, and T with respect to time
        Args:
            t (float): the time
        """
        self.T_n.assign(self.T)
        value = f.Constant(T_spline(t))
        self.T.assign(f.interpolate(value, self.T.function_space()))

# now I want to define the temperature for the model
my_model.T = CustomT()
```

The idea is to create a custom temperature class by inheriting from the `FESTIM.Temperature` class.
We can then override the `.update()` method (see [the original method here](https://github.com/RemDelaporteMathurin/FESTIM/blob/cbf6f779cbcc368595de567e1ddc639add98c214/festim/temperature/temperature.py#L43-L51)) to make use of `T_spline`

**Comment by RemDelaporteMathurin** [comment]
Just realising now you may need to give the initial temperature on the instanciation of `CustomT()`

```python
my_model.T = CustomT(value=300)
```

**Comment by nickwinz** [comment]
Thanks again @RemDelaporteMathurin , that works great!
