### ISSUE TITLE
Mesh Vertices should accept a list

### ISSUE THREAD

**Issue by jhdark** [festim-dev/FESTIM#597]
The vertices argument requires a shape at the moment, meaning it has to be an array. We could add a simple conversion to numpy array in case vertices are a list.

**Comment by RemDelaporteMathurin** [comment]
You can do that in the setter method of `vertices`

**Comment by RemDelaporteMathurin** [comment]
In the current code this is what we do:
https://github.com/RemDelaporteMathurin/FESTIM/blob/5c18f0fa7c824b0cf7ab80547aab447163fe258f/festim/meshing/mesh_from_vertices.py#L27

This ensures that vertices are a numpy array when passed to the mesher
