### ISSUE TITLE
Only update DirichletBC when needed

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/FESTIM#611]
As discussed in #609 , we need to find a way to only update the `DirichletBC` when it is needed (_ie_ when one of the parameters has changed).

At the moment, if the `DirichletBC` is a `fem.Function,` the expression is reinterpolated at every time step even when it's not needed.

https://github.com/RemDelaporteMathurin/FESTIM/blob/b96c636ae9f01032b6bac38dbe86259b011c4b7d/festim/boundary_conditions/dirichlet_bc.py#L151

Ideally we would only reinterpolate it if either:
- it is time dependent
- it is temperature dependent and the temperature has changed

The first check can be done at the `DiricheltBC` level.
But the second check has to be done at the `Problem` level.

Maybe a solution would be to have a boolean attribute `time_dependent` that is set when calling `.initialise()`.

Then in `.run()` have something like
```python
            for bc in self.boundary_conditions:
                if bc.time_dependent:
                    bc.update(float(self.t))
```

**Comment by RemDelaporteMathurin** [comment]
@jhdark has this been fixed?

**Comment by jhdark** [comment]
Yep, was covered in #619
