### ISSUE TITLE
Formatting Issues With Exporting Mobile Concentration Files in Workshop task1

### ISSUE THREAD

**Issue by ee-nn** [festim-dev/FESTIM#672]
I am trying out FESTIM for the first time and am starting to work my way through the workshop notebooks. I am running version 1.0 in Google Colab, and after figuring out how to get FEniCS installed I was able to run cells 1-8 with no problem. However, upon trying to retrieve the data for plotting I get the following error: 
```
import matplotlib.pyplot as plt
import numpy as np

data = np.genfromtxt(results_folder + "/mobile_concentration_100s.txt")

plt.plot(data[:,0], data[:,1])
plt.show()

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-14-c1e47a4b847f> in <cell line: 4>()
      2 import numpy as np
      3 
----> 4 data = np.genfromtxt(results_folder + "/mobile_concentration_100s.txt")
      5 
      6 plt.plot(data[:,0], data[:,1])

/usr/local/lib/python3.10/dist-packages/numpy/lib/_datasource.py in open(self, path, mode, encoding, newline)
    531                                       encoding=encoding, newline=newline)
    532         else:
--> 533             raise FileNotFoundError(f"{path} not found.")
    534 
    535 

FileNotFoundError: /content/drive/My Drive/FESTIM/task1/mobile_concentration_100s.txt not found.
```
I looked at the naming of the output file and there seems to be a formatting error for `mobile_concentration_*.txt`. In particular, there is a floating point precision error when appending the timestamp to the end of the filename it is `mobile_concentration_99.9999999999986s.txt`. 

I have corresponded with Remi on this and he says that this is a quick fix that will be addressed in the next version of the code. In the meantime, one can get around the issue by either installing a different version, as provided by Remi: 
> Just fyi, you can install any released version of the code like:
> 
> pip install festim==1.0
> 
> but also a github branch:
> 
> pip install git+https://github.com/festim-dev/festim@main
> pip install git+https://github.com/festim-dev/festim@fenicsx
> 
> but even the version of the code at a specific commit:
> 
> pip install git+https://github.com/festim-dev/festim@56089a5
Of course, this opens the possibility of other bugs, but might help get around this formatting issue for now until a stable version of FESTIM with this bug fix comes out. 

Hope this helps anyone else for which this was causing confusion!

**Comment by RemDelaporteMathurin** [comment]
A solution would be to either:


1. replace this line by

```python
header = f"x,t={current_time:.2e}s"
```


2. modify `is_it_time_to_export` ([here](https://github.com/festim-dev/FESTIM/blob/56089a544a7f21e2d9fe4c1b18d3b17ec7396509/festim/exports/txt_export.py#L37-L43)) so that it returns the user-input time and then use this user-input time in the header [instead of `current_time`](https://github.com/festim-dev/FESTIM/blob/56089a544a7f21e2d9fe4c1b18d3b17ec7396509/festim/exports/txt_export.py#L63) which may have a lot of decimals!

**Comment by KulaginVladimir** [comment]
@ee-nn, @RemDelaporteMathurin, It seems to me that both solutions can be combined together. The first one will make headers of txt-files more elegant for the case, when export is made at all timesteps, i.e. `TXTExport.times = None`. The second one is indeed better when the required times for export are provided. Imagine that we want to export data at `t=1001` and `t=1002`. In this case, we'll get two columns with the same name. Not really a problem, but can be improved by implementing the second suggestion.

**Comment by RemDelaporteMathurin** [comment]
@KulaginVladimir you're correct we could end up with two columns with the same name. We could expose the format (eg .2e, .2f, .4e etc.) to the users
