### ISSUE TITLE
`TXTExports` & `TXTExport` features

### ISSUE THREAD

**Issue by KulaginVladimir** [festim-dev/FESTIM#675]
`TXTExport` & `TXTExports` classes can be modified based on two points:

1. Following the [discourse topic](https://festim.discourse.group/t/file-formatting-bug-in-the-task4-workshop-file/25/4), users might need to provide the desired times for `TXTExport` & `TXTExports` in `Stepsize.milestones` to ensure that data is actually exported at these times. As @RemDelaporteMathurin suggested, this situation can be improved, if the missing `TXTExport.times` are added to `Stepsize.milestones` during initialisation of the model. 

2. If I'm not mistaken, the current `TXTExports` class won't export anything if a user doesn't provide `TXTExports.times`. However, the `TXTExport` class alows users to export the needed data at all timesteps, if `TXTExport.times` are not provided. Therefore, the `TXTExports` can be modified a bit to allow users to export the results at all timesteps. I suppose, it can be done as follows:

```python
class TXTExports:
    def __init__(self, fields=[], labels=[], times=None, folder=None) -> None:
        self.fields = fields
        if len(self.fields) != len(labels):
            raise ValueError(
                "Number of fields to be exported "
                "doesn't match number of labels in txt exports"
            )
        if times is not None:
            self.times = sorted(times)
        self.labels = labels
        self.folder = folder
        self.exports = []
        for function, label in zip(self.fields, self.labels):
            self.exports.append(TXTExport(function, label, folder, times))
```

**Comment by RemDelaporteMathurin** [comment]
@KulaginVladimir thanks for kicking off the discussion.

About the first point, I agree we should ensure that if users don't provide milestones but provide times for the TXTExport then we need to add these times to the milestones (and maybe raise a warning or something).

About the second point, I don't know if we want to keep supporting for `TXTExports` (plural). I don't know if it's used a lot or not. The only added value is to be able to define `times` and `folder` once. On the other hand I think your fix can work. So maybe we can implement it and add a `DeprecationWarning` specifying we will deprecate this class in the next minor release? what do you think?

**Comment by KulaginVladimir** [comment]
@RemDelaporteMathurin 

> About the second point, I don't know if we want to keep supporting for TXTExports (plural). I don't know if it's used a lot or not. The only added value is to be able to define times and folder once. On the other hand I think your fix can work. So maybe we can implement it and add a DeprecationWarning specifying we will deprecate this class in the next minor release? what do you think?

I think your suggestion is reasonable. Personally, `TXTExports` appeared to me only in Task4 of FESTIM Workshop. 

Shall I open a new PR to start implementing these minor modifications including warning messages to users?

**Comment by RemDelaporteMathurin** [comment]
Sure feel free to open a PR!
