### ISSUE TITLE
[BUG] derived_quantities.derived_quantities no longer works with v1.2

### ISSUE THREAD

**Issue by jhdark** [festim-dev/FESTIM#724]
**Describe the bug**
This wasn't supposed to be a breaking change with v1.2 by giving a list of derived quantities to the .derived_quantities attribute raises an error:

```
Traceback (most recent call last):
  File "/home/jdark/repos/eurofusion_FW_model/mwe.py", line 3, in <module>
    my_derived_quantities = F.DerivedQuantities()
                            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jdark/anaconda3/envs/testing/lib/python3.12/site-packages/festim/exports/derived_quantities/derived_quantities.py", line 36, in __init__
    if not isinstance(*args, list):
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: isinstance expected 2 arguments, got 1
```

**To Reproduce**
```python3
import festim as F

my_derived_quantities = F.DerivedQuantities()
my_derived_quantities.derived_quantities = [
    F.TotalVolume("test", volume=1),
]
```

**Comment by RemDelaporteMathurin** [comment]
Confirm this bug on 1.2 and on main

I would open a patch branch (`patch-1.2.1`) from the v1.2 tag and then create a release from this patch branch (`patch-1.2.1`) so that we don't release the rest. Then merge branch `patch-1.2.1` into `main`.

**Comment by KulaginVladimir** [comment]
In general, I thought it should work like:
```python
import festim as F

my_derived_quantities = F.DerivedQuantities([])
my_derived_quantities.derived_quantities = [
    F.TotalVolume("test", volume=1),
]
```

**Comment by RemDelaporteMathurin** [comment]
We should also allow for the way @jhdark uses it in the MWE to avoid breaking functionality

It shouldn't be too hard to fix

**Comment by KulaginVladimir** [comment]
I guess, just to modify `__init__`
