### ISSUE TITLE
Update documentation for new adaptive timestepping arguments

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/FESTIM#775]
Following #698 we need to update the documentation of the stepsize;

https://festim.readthedocs.io/en/latest/userguide/stepsize.html#stepsize

@KulaginVladimir do you want to be assigned to this?

**Comment by KulaginVladimir** [comment]
Yep, I don't mind. 

If #734 is planned to be merged soon, I can also add documentation on `CustomSolver`
