### ISSUE TITLE
Update the information in the XDMF section of the documentation

### ISSUE THREAD

**Issue by XinShen-CHN** [festim-dev/FESTIM#799]
Additional information can be added after "The file can then be opened in Paraview or any other software that can read XDMF files." in the XDMF section of the documentation as:

Here are some tips for using Paraview:

- Make sure to have the h5 file in the same directory as the XDMF file
- Open the XDMF file with Paraview then select the reader Xdmf3 Reader S
- Edit the colour map and rescale the colourbar to present a proper view of the result
- Etc

**Comment by RemDelaporteMathurin** [comment]
Hi @XinShen-CHN thanks for raising this issue. You're [not the only one](https://festim.discourse.group/t/cant-open-xdmf-files-with-paraview/55/2) who ran into this issue.

Thank you for contributing to FESTIM! ❤️ 

I think a good place for this would be the [XDMF export section in the documentation](https://festim.readthedocs.io/en/stable/userguide/export_post_processing.html#xdmf-export). To make modifications to this page, refer to this file where you'll find the relevant section:
https://github.com/festim-dev/FESTIM/blob/362cf71dcbb43089da81851830b40c0c37261152/docs/source/userguide/export_post_processing.rst?plain=1#L19-L21

You can read other parts of the documentation sources to see how to add images to the docs.
For example the SALOME guide:
https://github.com/festim-dev/FESTIM/blob/362cf71dcbb43089da81851830b40c0c37261152/docs/source/userguide/mesh.rst?plain=1#L83-L98

Please let us know if you have some issues in the workflow (using git for instance)!

**Comment by RemDelaporteMathurin** [comment]
I think a good thing to add as well would be a link to the [Paraview tutorials page](https://www.paraview.org/tutorials/). What do you think?

**Comment by XinShen-CHN** [comment]
@RemDelaporteMathurin 
It sounds good to add the Paraview tutorials page as well!

Thank you for the support! I'll try.

**Comment by XinShen-CHN** [comment]
@RemDelaporteMathurin I've submitted a branch but I'm not sure if it is successful.

**Comment by RemDelaporteMathurin** [comment]
@XinShen-CHN i can see your new branch on your forked repository! 

Now you can open a Pull Request (PR). To do so, go on the PR tab on the FESTIM-dev/FESTIM repo and create a new pull request from your branch
