### ISSUE TITLE
[BUG] trap id is None if append is used

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/FESTIM#804]
**Describe the bug**
When a trap is appended to the list of traps then its id is None and we can't perform derived quantity calculations on it.

**To Reproduce**

MWE

```python
import festim as F
import numpy as np


model = F.Simulation()
model.mesh = F.MeshFromVertices(np.linspace(0, 1, num=100))

model.materials = F.Material(id=1, D_0=1, E_D=0, borders=[0, 1])

model.traps = [F.Trap(k_0=1, E_k=0, E_p=0, p_0=1, density=1, materials=model.materials)]

model.traps.append(
    F.Trap(k_0=1, E_k=0, E_p=0, p_0=1, density=1, materials=model.materials)
)


model.T = F.Temperature(500)

model.settings = F.Settings(
    absolute_tolerance=1e-10,
    relative_tolerance=1e-10,
    transient=False,
)

model.initialise()

for trap in model.traps:
    print(trap.id)
    assert trap.id is not None
```

**Comment by KulaginVladimir** [comment]
This bug concerns each overwritten method of list.

**Comment by RemDelaporteMathurin** [comment]
Yes, which means we need to assign ids elsewhere, or, find a way to trigger this every time we change the elements

**Comment by RemDelaporteMathurin** [comment]
After looking at the code a little bit it would seem that the best way to go (and most straightforward) is to move these lines somewhere in `initialise` https://github.com/festim-dev/FESTIM/blob/1add5fc412427c02ed7714d3afc656e81a1e1745/festim/concentration/traps/traps.py#L24-L27

**Comment by KulaginVladimir** [comment]
Yes, otherwise we'd have to modify existing `Traps` methods and other (e.g. `pop`). Though, moving id assigment from `__init__` would require changing tests.

**Comment by KulaginVladimir** [comment]
Does it make sense to add an additional check `if trap.id is None` in this method?
https://github.com/festim-dev/FESTIM/blob/1add5fc412427c02ed7714d3afc656e81a1e1745/festim/concentration/traps/traps.py#L70-L72

so it'd be:
```python
def make_traps_materials(self, materials):
    for i, trap in enumerate(self, 1):
        if trap.id is None:
            trap.id = i
        trap.make_materials(materials)
``` 

Therefore, we  would not have to re-write the tests and the ids would be added after `Simulation.initialise()`, since `make_traps_materials` are called during `h_transport_problem.initialise`

**Comment by RemDelaporteMathurin** [comment]
The only issue that I have with this is that the method `make_traps_materials` now does two things and the name isn't completely right anymore.

Maybe we don't need this function at all and these four lines can simply go in `h_transport_problem.initialise()` ?

**Comment by KulaginVladimir** [comment]
hm, maybe. Though I'd keep the methods for traps in `Traps`. Another option is to define a method for `Traps`: `check_trap_ids`. Call it during `Traps.__init__` and `h_transport_problem.initialise()`

**Comment by RemDelaporteMathurin** [comment]
I don't like calling it in two places. I think just `h_transport_problem.initialise()` should be enough. Plus it should be named `assign_trap_ids` imo

**Comment by KulaginVladimir** [comment]
I think there is an issue with id assignment. Assume that `model.traps` has the following list of ids: `[1, None, 2, 3]`. The initialisation will result in `[1,2,2,3]`, won't it? 

Shall we modify this method to assign unique ids?

**Comment by RemDelaporteMathurin** [comment]
You are correct this is an issue. Maybe users should not be allowed to `id` should not set the id of a trap then. I don't think I've ever seen people do `F.Trap(id=2, ....)` anyway

**Comment by KulaginVladimir** [comment]
I suppose, the only benefit from a user-defined `id` is that users can mark and pick up a specific trap to analyse it further.

**Comment by RemDelaporteMathurin** [comment]
In that case I would rather give them names rather than ids

**Comment by KulaginVladimir** [comment]
Alright. For this particular bug, what'd be enough to fix it? It might be either a small fix with `assign_trap_ids` or a larger fix with an additional change of the `Trap` class.

**Comment by RemDelaporteMathurin** [comment]
Let's go for the small fix for now just because we know that the other bug you described won't be an issue since users don't use id for traps, and later we can remove this argument or replace it by a name argument. How does it sound?

**Comment by KulaginVladimir** [comment]
OK
