### ISSUE TITLE
Soret effect in cylindrical/spherical coordinates

### ISSUE THREAD

**Issue by KulaginVladimir** [festim-dev/FESTIM#818]
Currently, the Soret effect can be used with cartesian meshes. It would be nice to extend the functionality for cylindrical and spherical cases.

**Comment by RemDelaporteMathurin** [comment]
Yep, that's my bad.

At the time I didn't need Soret for cylindrical applications and I was too lazy to figure out how/if the equations would change for Soret in cylindrical (I guess so?).

**Comment by KulaginVladimir** [comment]
We just have to use a proper gradient, no? So, the Soret term in the form would be similar to the Fick diffusion term.

**Comment by RemDelaporteMathurin** [comment]
Yep, in theory that's all.

We'll need to have a verification case for this formulation (that could go in https://github.com/festim-dev/V-V-report/issues/64)

**Comment by KulaginVladimir** [comment]
I can do it, since I'd need Soret in cylindrical coordinates. 

Moreover, if #723 is going to be solved before v1.3, I can try to make it in time too.
