### ISSUE TITLE
Store user logos locally to avoid missing markers in map

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/FESTIM#824]
At the moment, we have URL links for logos in the user map JSON file.
https://github.com/festim-dev/FESTIM/blob/4cf700be5e1cf86a2cd1a5f2e869203edab64f0a/docs/source/map.json#L13-L16

However, this sometimes doesn't work either because the URL changes or maybe the request isn't authorised.
It produces this:

![image](https://github.com/user-attachments/assets/1f125dbc-20d6-4491-b7b8-e5885336ff44)

To fix it, a solution would be to store the logo locally in the `docs` directory instead of fetching it from the URL.

**Comment by XinShen-CHN** [comment]
Is the method of adding the logo locally the same as adding other images?

**Comment by RemDelaporteMathurin** [comment]
> Is the method of adding the logo locally the same as adding other images?

Adding the logos yes.

Then we require some changes to this script (responsible for generating the map) to make it work with non-URL images
https://github.com/festim-dev/FESTIM/blob/f7915f02c287be4b2f310df3bd3c461bcf02cf2f/docs/source/map.py#L50-L67

**Comment by XinShen-CHN** [comment]
> Then we require some changes to this script (responsible for generating the map) to make it work with non-URL images

Does it mean replace all the URL with local logo images?

**Comment by RemDelaporteMathurin** [comment]
> Does it mean replace all the URL with local logo images?

Yes. Using the URL has proven to be too unreliable and local images would work better

**Comment by XinShen-CHN** [comment]
> Yes. Using the URL has proven to be too unreliable and local images would work better

I see. I'll try to do it.

**Comment by XinShen-CHN** [comment]
> Then we require some changes to this script (responsible for generating the map) to make it work with non-URL images
> 
> https://github.com/festim-dev/FESTIM/blob/f7915f02c287be4b2f310df3bd3c461bcf02cf2f/docs/source/map.py#L50-L67

I think I can help with gathering all the logo images for [FESTIM/docs/source/map.json](https://github.com/festim-dev/FESTIM/blob/4cf700be5e1cf86a2cd1a5f2e869203edab64f0a/docs/source/map.json#L13-L16). But I might have no idea of making changes in [FESTIM/docs/source/map.py](https://github.com/festim-dev/FESTIM/blob/f7915f02c287be4b2f310df3bd3c461bcf02cf2f/docs/source/map.py#L50-L67)

Lines 50 to 67 in [f7915f0](https://github.com/festim-dev/FESTIM/commit/f7915f02c287be4b2f310df3bd3c461bcf02cf2f).

**Comment by RemDelaporteMathurin** [comment]
@XinShen-CHN 

I think that you would need to add these lines:

```python
        if "path" in feature["properties"]:
            url = feature["properties"]["path"]
            image_dimensions = Image.open(url).size
```

after https://github.com/festim-dev/FESTIM/blob/f7915f02c287be4b2f310df3bd3c461bcf02cf2f/docs/source/map.py#L58-L59


This will look for a key `"path"` in the JSON file with the local path to the image and set the value of `url` accordingly.

For example:

```json
            "properties": {
                "name": "University of Surrey",
                "path": "images/user_logos/university_surrey.png"
            }
```

If you do that for all the properties then you can remove all the URL related code in `map.py`.

Or have another if statement:

```python
        if "url" in feature["properties"]:
            url = feature["properties"]["url"]
            if url == "URL_PLACEHOLDER":
                url = "https://upload.wikimedia.org/wikipedia/commons/9/92/LOGO_CEA_ORIGINAL.svg"
            coordinates = feature["geometry"]["coordinates"]

            # Get the dimensions of the image from URL
            image_dimensions = get_image_dimensions_from_url(url)

        elif "path" in feature["properties"]:
            url = feature["properties"]["path"]
            image_dimensions = Image.open(url).size
```

**Comment by XinShen-CHN** [comment]
@RemDelaporteMathurin Thank you very much! I'll try.
