### ISSUE TITLE
Add new mpi4py requirement in docs

### ISSUE THREAD

**Issue by jhdark** [festim-dev/FESTIM#834]
with the new change to the fenics conda environment we should add the specification for the mpi4py version in the installation documentation.

We also need to update the CI cases when installing the environment to:
```
conda install -c conda-forge fenics numpy=1.24 mpi4py<4
```

**Comment by RemDelaporteMathurin** [comment]
Will this still be an issue when https://github.com/conda-forge/fenics-feedstock/issues/212 is fixed?

**Comment by RemDelaporteMathurin** [comment]
This issue seems to have been fixed https://github.com/conda-forge/fenics-feedstock/issues/212#issuecomment-2268220164

Closing this
