### ISSUE TITLE
Documentation: typo `value` not in code

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/FESTIM#843]
https://github.com/festim-dev/FESTIM/blob/31864c86690750ab854942c82110c3f711187246/docs/source/userguide/boundary_conditions.rst?plain=1#L32

Here value (single quotes) should be ` ``value`` ` (double quotes)

![image](https://github.com/user-attachments/assets/88995613-201f-448e-80f4-8acfa8357d24)

**Comment by XinShen-CHN** [comment]
Hi Remi, I think I can help with this simple improvement.

**Comment by RemDelaporteMathurin** [comment]
Hi @XinShen-CHN sure go for it 😄
