### ISSUE TITLE
TXT export: store data in memory and write only at last timestep

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/FESTIM#863]
@jhdark suggested that instead of writing the TXT at each timestep, we could store the data in memory and write everything at the last time step.

We could have a user argument to choose the behaviour.

@KulaginVladimir what do you think?

**Comment by KulaginVladimir** [comment]
> We could have a user argument to choose the behaviour.

Makes sense.

**Comment by KulaginVladimir** [comment]
> We could have a user argument to choose the behaviour.

Do we need to write data at each timestep? 

In the current implementation, `TXTExport` writes data -> reads old data and append new -> writes data, and so on. The only benefit I see is that at some timestep we can run out of memory and get an error. However, we nonetherless read the whole dataset at each call of `TXTExport.write()`

**Comment by RemDelaporteMathurin** [comment]
We are working with numpy arrays so it's unlikely that we will run out of memory.

Plus I don't see how not writing the data at each timestep would solve this? Maybe there's something I don't get here
