### ISSUE TITLE
Raise error if spherical coordinates are used for non-1D geometries

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/FESTIM#876]
In https://github.com/festim-dev/V-V-report/pull/74 we realised that spherical coordinates could be used on 2D geometries.

This is not possible and we should have an error raised when users do this

**Comment by KulaginVladimir** [comment]
@RemDelaporteMathurin 
A similar error is needed if cylindrical coordinates are used in a 3D case, right?

**Comment by RemDelaporteMathurin** [comment]
Yes!
