### ISSUE TITLE
[BUG] 1D simulations with several materials and no borders

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/FESTIM#926]
**Describe the bug**
Users can run 1D sims with multiple materials without specifying any `borders`.

When this happens, FESTIM acts as if the materials where defined everywhere. This means the meshtags contain only one value (I believe the last entry of `.materials`.

This should throw an error.

**To Reproduce**
Run the following:

```python
import festim as F


my_model = F.Simulation()
my_model.mesh = F.MeshFromVertices(vertices=[0, 1, 2, 3, 4, 5])

mat1 = F.Material(id=1, D_0=1, E_D=0)  # borders are not specified
mat2 = F.Material(id=2, D_0=3, E_D=0)
my_model.materials = [mat1, mat2]

my_model.T = 800

my_model.boundary_conditions = [
    F.DirichletBC(value=F.x, field=0, surfaces=[1, 2]),
]

my_model.settings = F.Settings(
    absolute_tolerance=1e-10,
    relative_tolerance=1e-10,
    transient=False,
)

my_model.initialise()
my_model.run()

```

**Expected behavior**
An error should be raised.

**Comment by KulaginVladimir** [comment]
it is #911, no?
